In [ ]:
                                                       #  PreproceDatassing with Pandas #

In [ ]:
## 1. How can you load a CSV file into your data analysis environment?

In [43]:
import pandas as pd

In [10]:
df = pd.read_csv('/employee_data.csv',sep="~")

In [11]:
df

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
0,1,NaN,34,Female,NaN,HR,2020-01-01,0
1,2,David,26,Male,89565.527086,Engineering,2020-01-02,0
2,3,Alice,50,Male,80200.507563,Engineering,2020-01-03,0
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0
4,5,Charlie,30,Male,71868.505106,Engineering,2020-01-05,0
...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0
997,998,David,21,Female,96681.365054,HR,2022-09-24,0
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0

In [ ]:
## How can you inspect the first few rows of a dataset?

In [14]:
df.head(20)

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
0,1,NaN,34,Female,NaN,HR,2020-01-01,0
1,2,David,26,Male,89565.527086,Engineering,2020-01-02,0
2,3,Alice,50,Male,80200.507563,Engineering,2020-01-03,0
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0
4,5,Charlie,30,Male,71868.505106,Engineering,2020-01-05,0
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0
6,7,Alice,65,Female,80606.713429,Marketing,2020-01-07,0
7,8,Alice,46,Male,NaN,Marketing,2020-01-08,0
8,9,Charlie,30,Male,45777.264812,Marketing,2020-01-09,0
9,10,Bob,63,Male,92100.440174,Finance,2020-01-10,0
10,11,Charlie,52,Male,48084.031979,Engineering,2020-01-11,0
11,12,Charlie,23,Female,78224.491603,Engineering,2020-01-12,0
12,13,Charlie,35,Female,38700.880468,HR,2020-01-13,1
13,14,Charlie,68,Female,70533.384263,Engineering,2020-01-14,1
14,15,David,22,Male,98054.699601,HR,2020-01-15,1
15,16,Alice,64,Male,61281.437182,Finance,2020-01-16,1
16,17,David,42,Female,89842.055204,Marketing,2020-01-17,1
17,18,David,19,Male,101590.496471,Marketing,2020-01-18,0
18,19,David,27,Male,113446.003753,Marketing,2020-01-19,0
19,20,Charlie,47,Male,NaN,Engineering,2020-01-20,0

In [ ]:
## How can you get a summary of a DataFrame?

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           1000 non-null   int64
 1   Name         999 non-null    object
 2   Age          1000 non-null   int64
 3   Gender       1000 non-null   object
 4   Salary       1000 non-null   float64
 5   Department   1000 non-null   object
 6   JoiningDate  1000 non-null   object
 7   Attrition    1000 non-null   int64
dtypes: float64(1), int64(3), object(4)
memory usage: 62.6+ KB

In [19]:
df.describe()

                ID          Age        Salary    Attrition
count  1000.000000  1000.000000  9.090000e+02  1000.000000
mean    500.500000    39.591000  1.553532e+12     0.201000
std     288.819436    19.313175  1.860845e+13     0.400949
min       1.000000     0.000000  0.000000e+00     0.000000
25%     250.750000    26.000000  5.258700e+04     0.000000
50%     500.500000    41.500000  7.566707e+04     0.000000
75%     750.250000    55.000000  9.805923e+04     0.000000
max    1000.000000    69.000000  4.829782e+14     1.000000

In [ ]:
## How can you handle a scenario with missing data in a dataset?

In [29]:
df.isnull().sum()

ID             0
Name           1
Age            0
Gender         0
Salary         0
Department     0
JoiningDate    0
Attrition      0
dtype: int64

In [31]:
df['Salary'].fillna(0, inplace=True)

In [33]:
df.isnull().sum()

ID             0
Name           1
Age            0
Gender         0
Salary         0
Department     0
JoiningDate    0
Attrition      0
dtype: int64

In [34]:
# How can you drop rows with missing values specifically in certain columns of a DataFrame?

In [36]:
type(df)

pandas.core.frame.DataFrame

In [39]:
df.dropna(subset=['Salary', 'Name'], inplace= True)

In [40]:
df.head()

   ID     Name  Age  Gender        Salary   Department JoiningDate  Attrition
1   2    David   26    Male  89565.527086  Engineering  2020-01-02          0
2   3    Alice   50    Male  80200.507563  Engineering  2020-01-03          0
3   4  Charlie   37  Female  95758.545922           HR  2020-01-04          0
4   5  Charlie   30    Male  71868.505106  Engineering  2020-01-05          0
5   6    David   45    Male  35412.810834      Finance  2020-01-06          0

In [41]:
# How can you clean duplicate entries in a dataset?

In [61]:
df.drop_duplicates()

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
1,2,David,26,Male,89565.527086,Engineering,2020-01-02,0
2,3,Alice,50,Male,80200.507563,Engineering,2020-01-03,0
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0
4,5,Charlie,30,Male,71868.505106,Engineering,2020-01-05,0
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0
...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0
997,998,David,21,Female,96681.365054,HR,2022-09-24,0
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0

In [45]:
df.drop_duplicates(inplace=True)

In [47]:
# How can you select rows where 'Age' is greater than 50 and display only the 'Name' and 'Salary' columns?

In [48]:
## df.loc[rows, column]

In [62]:
df.loc[df['Age'] >50, ['Name', 'Salary']]

        Name         Salary
6      Alice   80606.713429
9        Bob   92100.440174
10   Charlie   48084.031979
13   Charlie   70533.384263
15     Alice   61281.437182
..       ...            ...
985      Bob   34889.883134
991    David   54855.260204
992      Bob   93627.883871
994    David  105540.464312
999  Charlie   39170.314926

[343 rows x 2 columns]

In [ ]:
# Select rows where 'Gender' is 'Female' and 'Department' is 'HR', then display 'Name' and 'Age'.

In [57]:
selected_df = df.loc[df['Age'] >50, ['Name', 'Salary']]

In [56]:
selecte_df = df.loc[(df['Gender'] == 'Female') & (df['Department'] == 'HR'), [ 'Gender', 'Age', 'Name', 'Salary']]

In [59]:
selecte_df

     Gender  Age     Name        Salary
3    Female   37  Charlie  95758.545922
12   Female   35  Charlie  38700.880468
21   Female    0    Alice  43717.441200
25   Female   35      Bob      0.000000
26   Female   49      Bob  76886.217954
..      ...  ...      ...           ...
980  Female   52    David  54426.844240
988  Female   41      Bob  30012.122370
989  Female   20    David  76001.622531
993  Female   30    David  35642.065946
997  Female   21    David  96681.365054

[118 rows x 4 columns]

In [63]:
# How do you set the 'Salary' to 100,000 for the row where 'ID' is 10?

In [67]:
df[df['ID'] == 10]

   ID Name  Age Gender    Salary Department JoiningDate  Attrition
9  10  Bob   63   Male  100000.0    Finance  2020-01-10          0

In [68]:
df.loc[df['ID'] == 10, 'Salary'] = 1000

In [69]:
df[df['ID'] == 10]

   ID Name  Age Gender  Salary Department JoiningDate  Attrition
9  10  Bob   63   Male  1000.0    Finance  2020-01-10          0

In [70]:
# How do you select the first 10 rows and the first 4 columns of a dataset?

In [71]:
df.iloc[:10, :4]

    ID     Name  Age  Gender
1    2    David   26    Male
2    3    Alice   50    Male
3    4  Charlie   37  Female
4    5  Charlie   30    Male
5    6    David   45    Male
6    7    Alice   65  Female
7    8    Alice   46    Male
8    9  Charlie   30    Male
9   10      Bob   63    Male
10  11  Charlie   52    Male

In [72]:
# How can you select the value located in the 5th row and 3rd column of a dataset?

In [73]:
df.iloc[5, 3]

'Female'

In [75]:
df.iloc[[2,4,6],[1,3,5]]

      Name  Gender Department
3  Charlie  Female         HR
5    David    Male    Finance
7    Alice    Male  Marketing

In [76]:
# how to filter all even number data in dataset ? (we can also use this simple code:- df.iloc[::2] )

In [79]:
df.loc[df['ID'] % 2 == 0]

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
1,2,David,26,Male,89565.527086,Engineering,2020-01-02,0
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0
7,8,Alice,46,Male,0.000000,Marketing,2020-01-08,0
9,10,Bob,63,Male,1000.000000,Finance,2020-01-10,0
...,...,...,...,...,...,...,...,...
991,992,David,52,Male,54855.260204,Finance,2022-09-18,0
993,994,David,30,Female,35642.065946,HR,2022-09-20,0
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0
997,998,David,21,Female,96681.365054,HR,2022-09-24,0
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0

In [80]:
# How do you set the 'Age' to 40 and 'Salary' to 80,000 for rows where 'Department' is 'Engineering' and 'Gender' is 'Male'?

In [84]:
selecte_df = df.loc[(df['Department'] == 'Engineering') & (df['Gender'] == 'Male'), ['Age', 'Salary']] = [40, 80000]

In [85]:
selecte_df

[40, 80000]

In [86]:
## Select every 10th row and every 2nd column starting from the 1st row and 2nd column?

In [87]:
df.iloc[::10, ::2]

      ID  Age         Salary JoiningDate
1      2   40   80000.000000  2020-01-02
11    12   23   78224.491603  2020-01-12
21    22    0   43717.441200  2020-01-22
31    32   43  104346.086723  2020-02-01
41    42   18       0.000000  2020-02-11
..   ...  ...            ...         ...
951  952   63   55290.404902  2022-08-09
961  962    0   84314.378644  2022-08-19
971  972   66   91435.549910  2022-08-29
981  982   37   74702.588054  2022-09-08
991  992   52   54855.260204  2022-09-18

[100 rows x 4 columns]

In [88]:
# How do you calculate the total sum of 'Salary' for each 'Department' in a dataset?

In [89]:
df.groupby('Department')['Salary'].sum()

Department
Engineering    2.701034e+14
Finance        1.196791e+14
HR             2.818147e+14
Marketing      7.405631e+14
Name: Salary, dtype: float64

In [90]:
## How can you count the number of employees in each 'Department' in a dataset?

In [91]:
df.groupby('Department')['Name'].count()

Department
Engineering    245
Finance        233
HR             271
Marketing      250
Name: Name, dtype: int64

In [92]:
## How do you compute the average 'Age' for each 'Gender' in a dataset?

In [93]:
df.groupby('Gender')['Age'].mean()

Gender
Female    39.169291
Male      40.258656
Name: Age, dtype: float64

In [94]:
## Calculate both the total and average 'Salary' for each 'Gender'?

In [95]:
df.groupby('Gender')['Salary'].agg(['sum', 'mean'])

                 sum          mean
Gender
Female  1.165284e+15  2.293866e+12
Male    2.468764e+14  5.028033e+11

In [96]:
## How do you calculate the total 'Salary' for each combination of 'Department' and 'Gender' in a dataset?

In [97]:
df.groupby(['Department', 'Gender'])['Salary'].sum()

Department   Gender
Engineering  Female    2.701033e+14
             Male      8.960000e+06
Finance      Female    1.196790e+14
             Male      7.340510e+06
HR           Female    1.086827e+14
             Male      1.731320e+14
Marketing    Female    6.668187e+14
             Male      7.374445e+13
Name: Salary, dtype: float64

In [98]:
## How do you filter out 'Departments' where the average 'Salary' is below 60,000 in a dataset?

In [99]:
df.groupby('Department')['Salary'].mean() < 60000

Department
Engineering    False
Finance        False
HR             False
Marketing      False
Name: Salary, dtype: bool

In [100]:
## How do you sort the DataFrame by 'Age' in ascending order?

In [101]:
df.sort_values(by='Age')

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
290,291,Alice,0,Female,116226.613211,HR,2020-10-17,1
147,148,Charlie,0,Female,73941.702332,Finance,2020-05-27,0
149,150,David,0,Male,59220.833420,Marketing,2020-05-29,0
507,508,Charlie,0,Female,67598.488135,Engineering,2021-05-22,1
494,495,Alice,0,Female,42664.037524,HR,2021-05-09,0
...,...,...,...,...,...,...,...,...
193,194,Charlie,69,Male,38855.608474,HR,2020-07-12,0
683,684,David,69,Male,60497.458440,HR,2021-11-14,0
910,911,Charlie,69,Male,48963.446748,Marketing,2022-06-29,0
958,959,Bob,69,Female,50342.609803,Marketing,2022-08-16,0
777,778,David,69,Male,42833.472967,Finance,2022-02-16,0

In [103]:
## How do you sort the DataFrame first by 'Department' in ascending order, and then by 'Salary' in descending order?

In [104]:
df.sort_values(by=['Department', 'Salary'], ascending=[True, False])

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
23,24,David,50,Female,1.134387e+14,Engineering,2020-01-24,0
425,426,Alice,55,Female,8.051509e+13,Engineering,2021-03-01,1
686,687,Bob,41,Female,7.614953e+13,Engineering,2021-11-17,1
913,914,Bob,46,Female,1.198039e+05,Engineering,2022-07-02,0
698,699,Bob,0,Female,1.193535e+05,Engineering,2021-11-29,0
...,...,...,...,...,...,...,...,...
786,787,Charlie,26,Female,0.000000e+00,Marketing,2022-02-25,1
805,806,David,55,Female,0.000000e+00,Marketing,2022-03-16,0
853,854,Charlie,68,Male,0.000000e+00,Marketing,2022-05-03,0
894,895,David,62,Female,0.000000e+00,Marketing,2022-06-13,0
948,949,Bob,60,Male,0.000000e+00,Marketing,2022-08-06,1

In [106]:
## How do you sort the DataFrame by 'JoiningDate' in ascending order, ensuring NaN values are placed at the end?

In [108]:
df.sort_values(by='Age', ascending=False).reset_index(drop=True)

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
0,959,Bob,69,Female,50342.609803,Marketing,2022-08-16,0
1,778,David,69,Male,42833.472967,Finance,2022-02-16,0
2,111,David,69,Male,0.000000,HR,2020-04-20,0
3,911,Charlie,69,Male,48963.446748,Marketing,2022-06-29,0
4,194,Charlie,69,Male,38855.608474,HR,2020-07-12,0
...,...,...,...,...,...,...,...,...
994,452,Bob,0,Male,53275.875140,Finance,2021-03-27,0
995,314,Charlie,0,Male,35836.823503,Finance,2020-11-09,0
996,800,Charlie,0,Female,116761.566641,HR,2022-03-10,0
997,317,Charlie,0,Female,80459.408497,Finance,2020-11-12,0
998,123,Bob,0,Female,63098.341579,HR,2020-05-02,0

In [109]:
## How do you rename the column 'EmployeeName' to 'Name' in a DataFrame?

In [110]:
df.rename(columns={'EmployeeName': 'Name'}, inplace=True)

In [112]:
df

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0
...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0
997,998,David,21,Female,96681.365054,HR,2022-09-24,0
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0

In [113]:
## How can you add a new column 'Bonus' that is 5% of the 'Salary' for each employee in a DataFrame?

In [119]:
df['salary_bonus'] = df['Salary'] * 0.05

In [120]:
df

,ID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition,salary_bonus
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0,4000.000000
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0,4000.000000
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0,4787.927296
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0,4000.000000
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0,1770.640542
...,...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0,1517.189652
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0,2610.707411
997,998,David,21,Female,96681.365054,HR,2022-09-24,0,4834.068253
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0,2923.215674
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0,1958.515746

In [116]:
## How do you rename the columns ['ID', 'JoiningYear'] to ['EmployeeID', 'YearJoined'] in a DataFrame?

In [124]:
df.rename(columns={'ID': 'EmployeeID', 'JoiningYear': 'YearJoined'}, inplace=True)

In [125]:
df

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition,salary_bonus
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0,4000.000000
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0,4000.000000
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0,4787.927296
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0,4000.000000
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0,1770.640542
...,...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0,1517.189652
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0,2610.707411
997,998,David,21,Female,96681.365054,HR,2022-09-24,0,4834.068253
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0,2923.215674
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0,1958.515746

In [126]:
## How can you add a new column 'Seniority' that labels employees as 'Senior' if their 'Age' is above 40, and 'Junior' otherwise, in a DataFrame?

In [128]:
df['Seniority'] = df['Age'].apply(lambda x: 'Senior' if x > 40 else 'Junior')

In [129]:
df

,EmployeeID,Name,Age,Gender,Salary,Department,JoiningDate,Attrition,salary_bonus,Seniority
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0,4000.000000,Junior
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0,4000.000000,Junior
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0,4787.927296,Junior
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0,4000.000000,Junior
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0,1770.640542,Senior
...,...,...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0,1517.189652,Senior
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0,2610.707411,Junior
997,998,David,21,Female,96681.365054,HR,2022-09-24,0,4834.068253,Junior
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0,2923.215674,Junior
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0,1958.515746,Senior

In [130]:
## How do you rename all columns to lowercase in a DataFrame?

In [152]:
df.rename(columns=str.lower, inplace=True)

In [153]:
df

,employeeid,name,age,gender,salary,department,joiningdate,attrition,salary_bonus,seniority
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0,4000.000000,Junior
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0,4000.000000,Junior
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0,4787.927296,Junior
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0,4000.000000,Junior
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0,1770.640542,Senior
...,...,...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0,1517.189652,Senior
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0,2610.707411,Junior
997,998,David,21,Female,96681.365054,HR,2022-09-24,0,4834.068253,Junior
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0,2923.215674,Junior
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0,1958.515746,Senior

In [140]:
## How can you replace all occurrences of 'Male' with 'M' in the 'Gender' column of a DataFrame?

In [141]:
df.replace({'Gender': {'Male': 'M'}}, inplace=True)

In [142]:
df

,EMPLOYEEID,NAME,AGE,GENDER,SALARY,DEPARTMENT,JOININGDATE,ATTRITION,SALARY_BONUS,SENIORITY
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0,4000.000000,Junior
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0,4000.000000,Junior
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0,4787.927296,Junior
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0,4000.000000,Junior
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0,1770.640542,Senior
...,...,...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0,1517.189652,Senior
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0,2610.707411,Junior
997,998,David,21,Female,96681.365054,HR,2022-09-24,0,4834.068253,Junior
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0,2923.215674,Junior
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0,1958.515746,Senior

In [156]:
## How do you remove a single column from a DataFrame?

In [158]:
df.rename(columns={'salary_bonus': 'bonus'}, inplace=True)

In [159]:
df

,employeeid,name,age,gender,salary,department,joiningdate,attrition,bonus,seniority
1,2,David,40,Male,80000.000000,Engineering,2020-01-02,0,4000.000000,Junior
2,3,Alice,40,Male,80000.000000,Engineering,2020-01-03,0,4000.000000,Junior
3,4,Charlie,37,Female,95758.545922,HR,2020-01-04,0,4787.927296,Junior
4,5,Charlie,40,Male,80000.000000,Engineering,2020-01-05,0,4000.000000,Junior
5,6,David,45,Male,35412.810834,Finance,2020-01-06,0,1770.640542,Senior
...,...,...,...,...,...,...,...,...,...,...
995,996,Alice,42,Female,30343.793039,Engineering,2022-09-22,0,1517.189652,Senior
996,997,Alice,26,Male,52214.148228,HR,2022-09-23,0,2610.707411,Junior
997,998,David,21,Female,96681.365054,HR,2022-09-24,0,4834.068253,Junior
998,999,David,31,Female,58464.313476,Engineering,2022-09-25,0,2923.215674,Junior
999,1000,Charlie,54,Female,39170.314926,Engineering,2022-09-26,0,1958.515746,Senior